site_name: Implantación de Sistemas Operativos
nav:
  - Inicio: index.md
  - Tema 1:
      - Introducción: tema1_1.md
      - Instalación: tema1_2.md
  - Acerca de: acerca.md
theme:
  name: readthedocs

